version: '3.9'

services:
  todo_db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db